name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger client deploy
        env:
          HOOK_URL: ${{ secrets.RENDER_CLIENT_DEPLOY_HOOK }}
        run: |
          if [ -n "$HOOK_URL" ]; then
            curl -X POST "$HOOK_URL"
          else
            echo "No client deploy hook configured."
          fi
      - name: Trigger server deploy
        env:
          HOOK_URL: ${{ secrets.RENDER_SERVER_DEPLOY_HOOK }}
        run: |
          if [ -n "$HOOK_URL" ]; then
            curl -X POST "$HOOK_URL"
          else
            echo "No server deploy hook configured."
          fi
